CREATE DATABASE retail_analytics;
USE retail_analytics;
CREATE TABLE retail_sales (S
    Invoice VARCHAR(20),
    StockCode VARCHAR(20),
    Description TEXT,
    Quantity INT,
    InvoiceDate DATETIME,
    Price FLOAT,
    CustomerID FLOAT,
    Country VARCHAR(50),
    Revenue FLOAT,
    Month INT,
    Year INT
);

USE retail_analytics;

LOAD DATA LOCAL INFILE 'C:/Users/c patil/Desktop/Retail-Analytics-Project/Notebooks/cleaned_retail_data.csv'
INTO TABLE retail_sales
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'C:/Users/c patil/Desktop/Retail-Analytics-Project/Notebooks/cleaned_retail_data.csv'
INTO TABLE retail_sales
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

USE retail_analytics;

SELECT * 
FROM retail_sales
LIMIT 10;

#Query 1 — Total Revenue
#Find the total revenue generated from all retail sales transactions.
SELECT 
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM retail_sales;


#Query 2 — Top Countries by Revenue
#Identify the top 10 countries generating the highest revenue.

SELECT 
    Country,
    ROUND(SUM(Revenue), 2) AS Revenue
FROM retail_sales
GROUP BY Country
ORDER BY Revenue DESC
LIMIT 10;


#Query 3 — Monthly Revenue Trend
#Analyze monthly revenue trends across different years.

SELECT 
    Year,
    Month,
    ROUND(SUM(Revenue), 2) AS Monthly_Revenue
FROM retail_sales
GROUP BY Year, Month
ORDER BY Year, Month;



#Query 4 — Top Customers
#Find the top 10 customers based on total spending.

SELECT 
    `Customer ID`,
    ROUND(SUM(Revenue), 2) AS Total_Spending
FROM retail_sales
GROUP BY `Customer ID`
ORDER BY Total_Spending DESC
LIMIT 10;


#Query 5 — Best Selling Products
#Identify the top 10 most sold products based on quantity.

SELECT 
    Description,
    SUM(Quantity) AS Total_Quantity_Sold
FROM retail_sales
GROUP BY Description
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;

#Query 6 — Average Order Value
#Calculate the average order value across all transactions.

SELECT 
    ROUND(AVG(Revenue), 2) AS Average_Order_Value
FROM retail_sales;


#Query 7 — Revenue by Year
#Find total yearly revenue generated by the business.

SELECT 
    Year,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM retail_sales
GROUP BY Year
ORDER BY Year;


#Query 8 — Top Products by Revenue
#Identify products generating the highest revenue.

SELECT 
    Description,
    ROUND(SUM(Revenue), 2) AS Product_Revenue
FROM retail_sales
GROUP BY Description
ORDER BY Product_Revenue DESC
LIMIT 10;


#Query 9 — Customer Purchase Frequency
#Find customers with the highest number of purchases.

SELECT 
    `Customer ID`,
    COUNT(DISTINCT Invoice) AS Total_Orders
FROM retail_sales
GROUP BY `Customer ID`
ORDER BY Total_Orders DESC
LIMIT 10;


#Query 10 — Country-wise Order Count
#Analyze total number of orders placed from each country.

SELECT 
    Country,
    COUNT(DISTINCT Invoice) AS Total_Orders
FROM retail_sales
GROUP BY Country
ORDER BY Total_Orders DESC;

#Query 11 — Highest Revenue Generating Month
#Find the month with the highest total revenue.

SELECT 
    Year,
    Month,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM retail_sales
GROUP BY Year, Month
ORDER BY Total_Revenue DESC
LIMIT 1;


#Query 12 — Lowest Revenue Generating Month
#Identify the month with the lowest revenue generation.

SELECT 
    Year,
    Month,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM retail_sales
GROUP BY Year, Month
ORDER BY Total_Revenue ASC
LIMIT 1;


#Query 13 — Unique Customers Count
#Calculate the total number of unique customers.

SELECT 
    COUNT(DISTINCT `Customer ID`) AS Unique_Customers
FROM retail_sales;


#Query 14 — Average Quantity per Order
#Find the average quantity of products purchased per transaction.

SELECT 
    ROUND(AVG(Quantity), 2) AS Average_Quantity
FROM retail_sales;


#Query 15 — Top Revenue Customers by Country
#Identify the highest spending customer from each country.

SELECT 
    Country,
    `Customer ID`,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM retail_sales
GROUP BY Country, `Customer ID`
ORDER BY Total_Revenue DESC;


#Query 16 — Rank Customers by Revenue
#Rank customers based on total revenue generated.

SELECT 
    `Customer ID`,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    RANK() OVER (
        ORDER BY SUM(Revenue) DESC
    ) AS Customer_Rank
FROM retail_sales
GROUP BY `Customer ID`;


#Query 17 — Running Monthly Revenue
#Calculate cumulative monthly revenue over time.

SELECT 
    Year,
    Month,
    ROUND(SUM(Revenue), 2) AS Monthly_Revenue,
    
    ROUND(
        SUM(SUM(Revenue)) OVER (
            ORDER BY Year, Month
        ), 2
    ) AS Running_Revenue
FROM retail_sales
GROUP BY Year, Month;

#Query 18 — Revenue Contribution Percentage
#Calculate each country's percentage contribution to total revenue.

SELECT 
    Country,
    
    ROUND(SUM(Revenue), 2) AS Country_Revenue,
    
    ROUND(
        (SUM(Revenue) / 
        (SELECT SUM(Revenue) FROM retail_sales)) * 100,
        2
    ) AS Revenue_Percentage
FROM retail_sales
GROUP BY Country
ORDER BY Revenue_Percentage DESC;

#Query 19 — Top Product per Country
#Identify the highest-selling product in each country.

WITH product_sales AS (
    
    SELECT
        Country,
        Description,
        SUM(Quantity) AS Total_Quantity,
        
        RANK() OVER (
            PARTITION BY Country
            ORDER BY SUM(Quantity) DESC
        ) AS product_rank
        
    FROM retail_sales
    
    GROUP BY Country, Description
)

SELECT *
FROM product_sales
WHERE product_rank = 1;


#Query 20 — High Value Customers
#Identify customers whose spending is higher than average customer spending.

SELECT 
    `Customer ID`,
    ROUND(SUM(Revenue), 2) AS Total_Spending
FROM retail_sales
GROUP BY `Customer ID`
HAVING SUM(Revenue) >
(
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM(Revenue) AS customer_total
        FROM retail_sales
        GROUP BY `Customer ID`
    ) AS avg_table
)
ORDER BY Total_Spending DESC;



#Query 21 — Dense Rank Products by Revenue
#Rank products based on total revenue using dense ranking.

SELECT 
    Description,
    
    ROUND(SUM(Revenue), 2) AS Product_Revenue,
    
    DENSE_RANK() OVER (
        ORDER BY SUM(Revenue) DESC
    ) AS Product_Rank
    
FROM retail_sales

GROUP BY Description;


#Query 22 — Average Revenue per Customer
#Calculate average revenue generated per customer.

SELECT 
    ROUND(
        SUM(Revenue) / COUNT(DISTINCT `Customer ID`),
        2
    ) AS Avg_Revenue_Per_Customer
FROM retail_sales;


#Query 23 — Repeat Customers
#Identify customers who placed more than one order.

SELECT 
    `Customer ID`,
    
    COUNT(DISTINCT Invoice) AS Total_Orders
    
FROM retail_sales

GROUP BY `Customer ID`

HAVING COUNT(DISTINCT Invoice) > 1

ORDER BY Total_Orders DESC;


#Query 24 — Monthly Growth Rate
#Calculate month-over-month revenue growth rate.

WITH monthly_revenue AS (
    
    SELECT
        Year,
        Month,
        SUM(Revenue) AS Revenue
        
    FROM retail_sales
    
    GROUP BY Year, Month
)

SELECT
    Year,
    Month,
    ROUND(Revenue, 2) AS Revenue,
    
    ROUND(
        (
            Revenue -
            LAG(Revenue) OVER (
                ORDER BY Year, Month
            )
        )
        /
        LAG(Revenue) OVER (
            ORDER BY Year, Month
        ) * 100,
        2
    ) AS Growth_Rate_Percentage
    
FROM monthly_revenue;


#Query 25 — Customer Lifetime Value (CLV)
#Calculate customer lifetime value based on total spending.

SELECT 
    `Customer ID`,
    
    ROUND(SUM(Revenue), 2) AS Customer_Lifetime_Value
    
FROM retail_sales

GROUP BY `Customer ID`

ORDER BY Customer_Lifetime_Value DESC;


#Query 26 — Top 5 Customers from Each Country
#Identify the top 5 highest spending customers from each country.

WITH customer_revenue AS (
    
    SELECT
        Country,
        `Customer ID`,
        ROUND(SUM(Revenue), 2) AS Total_Revenue,
        
        DENSE_RANK() OVER (
            PARTITION BY Country
            ORDER BY SUM(Revenue) DESC
        ) AS customer_rank
        
    FROM retail_sales
    
    GROUP BY Country, `Customer ID`
)

SELECT *
FROM customer_revenue
WHERE customer_rank <= 5;


#Query 27 — Revenue Category Classification
#Classify customers into revenue categories based on total spending.

SELECT 
    `Customer ID`,
    
    ROUND(SUM(Revenue), 2) AS Total_Spending,
    
    CASE
    
        WHEN SUM(Revenue) >= 10000
        THEN 'High Value'
        
        WHEN SUM(Revenue) >= 5000
        THEN 'Medium Value'
        
        ELSE 'Low Value'
        
    END AS Customer_Category
    
FROM retail_sales

GROUP BY `Customer ID`

ORDER BY Total_Spending DESC;


#Query 28 — Most Frequently Purchased Products
#Find products purchased most frequently across transactions.

SELECT 
    Description,
    
    COUNT(*) AS Purchase_Frequency
    
FROM retail_sales

GROUP BY Description

ORDER BY Purchase_Frequency DESC
LIMIT 10;


#Query 29 — Average Monthly Revenue
#Calculate average monthly revenue generated by the business.

SELECT 
    ROUND(
        AVG(monthly_revenue),
        2
    ) AS Avg_Monthly_Revenue
    
FROM (
    
    SELECT
        Year,
        Month,
        SUM(Revenue) AS monthly_revenue
        
    FROM retail_sales
    
    GROUP BY Year, Month
    
) AS monthly_table;


#Query 30 — Revenue Generated by Repeat Customers
#Calculate total revenue contributed by repeat customers.

SELECT 
    ROUND(SUM(Revenue), 2) AS Repeat_Customer_Revenue
    
FROM retail_sales

WHERE `Customer ID` IN (

    SELECT `Customer ID`
    
    FROM retail_sales
    
    GROUP BY `Customer ID`
    
    HAVING COUNT(DISTINCT Invoice) > 1
);